name: Pre-Release

# Run this job when a new pre-release is created on github.
# Then wait for all artifacts to be uploaded before releasing it.
on:
  release:
    types: [prereleased]
  # NOTE: uncomment the PR trigger to test changes
  # pull_request:
  #   branches: [ "master" ]    

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform-name: linux-amd64
          - os: macos-latest
            platform-name: macos-amd64
          - os: windows-latest
            platform-name: windows-amd64
            bin-extension: .exe

    steps:
      - uses: actions/checkout@v3
      
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.11.1.1189
          bb: 1.0.168
          
      - run: java --version
      - run: bb --version

      - name: Build binary
        run: bb native-image

      - name: Create archive
        run: tar -czf roam-to-csv-${{ github.event.release.tag_name }}-${{ matrix.platform-name }}.tar.gz roam-to-csv${{ matrix.bin-extension }}

      - name: Add binary to release
        if: github.event.release.tag_name
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          tag: ${{ github.event.release.tag_name }}
          artifacts: "roam-to-csv-${{ github.event.release.tag_name }}-${{ matrix.platform-name }}.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

  test-native:
    runs-on: ${{ matrix.os }}
    needs: [release]
    if: github.event.release.tag_name
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform-name: linux-amd64
          - os: macos-latest
            platform-name: macos-amd64
          - os: windows-latest
            platform-name: windows-amd64

    steps:
      - uses: actions/checkout@v3

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          bb: 1.0.168

      - run: curl -OL https://github.com/filipesilva/roam-to-csv/releases/download/${{ github.event.release.tag_name }}/roam-to-csv-${{ github.event.release.tag_name }}-${{ matrix.platform-name }}.tar.gz
      - run: tar -xvf roam-to-csv-${{ github.event.release.tag_name }}-${{ matrix.platform-name }}.tar.gz

      - name: run tests over native bin
        run: bb test --native
