name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform-name: linux-amd64
          - os: macos-latest
            platform-name: macos-amd64
          - os: windows-latest
            platform-name: windows-amd64
            bin-extension: .cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.1.0'
          java: 'java11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.3.855
          
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.4.6
          
      - run: java --version
      - run: bb --version

      - name: Build non-windows binary
        run: bb native-image
        if: matrix.os != 'windows-latest'

      - name: Build windows binary
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && bb native-image
        if: matrix.os == 'windows-latest'
        shell: cmd

      - name: Create archive
        run: tar -czf roam-to-csv-0.0.0-${{ matrix.platform-name }}.tar.gz roam-to-csv${{ matrix.bin-extension }}

      - name: Add binary to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          tag: "v0.0.1"
          artifacts: "roam-to-csv-0.0.0-${{ matrix.platform-name }}.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

