name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.1.0'
          java: 'java11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.3.855
          
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.4.6
          
      - run: java --version
      - run: bb --version

      - name: Build binary
        run: bb native-image

      - name: Create archive
        run: tar -czf roam-to-csv-0.0.1-linux-amd64.tar.gz roam-to-csv

      - name: Add binary to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          tag: "v0.0.1"
          artifacts: "roam-to-csv-0.0.0-linux-amd64.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

