name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.11.1.1189
          bb: 1.0.168

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: java --version
      - run: bb --version
      - run: node --version
      - run: yarn

      - name: run java tests
        run: bb test

      - name: build js lib
        run: bb js-lib

      - name: run js tests
        run: bb test --js
